services:
  bot:
    build: .
    restart: unless-stopped
    volumes:
      - ./data:/app/data:r
    environment:
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
  mongodb:
    image: mongo:4.4.6
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}

volumes:
  mongo-data:
