"""
Remove emoji from TagGroup

Revision ID: f105b088a0a3
Revises: f0f76bb9b563
Create Date: 2024-12-28 18:48:42.789013

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f105b088a0a3"
down_revision: str | None = "f0f76bb9b563"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tag_groups", "emojis")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tag_groups", sa.Column("emojis", sa.VARCHAR(), nullable=False))
    # ### end Alembic commands ###
