"""
Remove word_counter and student_info tables.

Revision ID: db3eb7114519
Revises: f105b088a0a3
Create Date: 2026-05-17 22:04:14.537549

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "db3eb7114519"
down_revision: str | None = "f105b088a0a3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("word_counter")
    op.drop_table("student_info")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "student_info",
        sa.Column("chat_id", sa.INTEGER(), nullable=False),
        sa.Column("student_id", sa.INTEGER(), nullable=False),
        sa.Column("name", sa.VARCHAR(), nullable=False),
        sa.Column("surname", sa.VARCHAR(), nullable=False),
        sa.Column("email", sa.VARCHAR(), nullable=False),
        sa.PrimaryKeyConstraint("chat_id", "student_id"),
    )
    op.create_table(
        "word_counter",
        sa.Column("chat_id", sa.INTEGER(), nullable=False),
        sa.Column("word", sa.VARCHAR(), nullable=False),
        sa.Column("count", sa.INTEGER(), nullable=False),
        sa.PrimaryKeyConstraint("chat_id", "word"),
    )
    # ### end Alembic commands ###
