name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  prek:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: j178/prek-action@6ad80277337ad479fe43bd70701c3f7f8aa74db3 # v2

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5

      - name: Install uv
        uses: astral-sh/setup-uv@5a095e7a2014a4212f075830d4f7277575a9d098 # v7
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install

      - name: Install dependencies
        run: uv sync --dev

      # TODO: Maybe move to prek once the official hook is released: https://github.com/astral-sh/ty/issues/269
      - name: Run typechecker
        run: uv run ty check

      - name: Run tests
        run: uv run pytest -v
